#:kivy 2.3.0

<MainScreen>:
    ItemList:
        id: item_list
        size_hint_y: 0.9
    
    AddItem:
        id: add_item
        size_hint_y: 0.1
        pos_hint: {'x': 0, 'y': 0}

<ItemList>:
    orientation: 'vertical'        

<AddItem>:
    orientation: 'horizontal'

    TextInput:
        id: todo_name
        hint_text: 'Add task'
        multiline: False

    Button:
        text: 'Add Item'
        on_press: root.on_add_item_button_click()
